name: deploy-s3
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'

      - name: Restore Yarn cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --non-interactive --frozen-lockfile

      - name: Build React App
        run: yarn run build

      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.S3_EXPLORER_BUCKET }} --delete
